### ISSUE TITLE
 not enough arguments in call to l.listener.Close

### ISSUE THREAD

**Issue by pedrooct** [go-ocf/go-coap#63]
Hi , when i try to install this package it gives me the following error:

# github.com/go-ocf/go-coap/net
../../go/src/github.com/go-ocf/go-coap/net/dtlslistener.go:126:25: not enough arguments in call to l.listener.Close
	have ()
	want (time.Duration)

I have already installed this package many times and today this is happening.

Help me please it's urgent !
Go version 1.12.9

Thank you.

**Comment by jkralik** [comment]
Hi. The issue is that pion/dtls changes API. go-coap is fixed to version 1.5.0 https://github.com/go-ocf/go-coap/blob/92481866bd1713e2c98a02933f472c0f8a28a91c/Gopkg.lock#L22
I locked to the new version 1.5.1 but it still use Close function without timeout argument.

To fix your issue you can use `dep` utility  (https://github.com/golang/dep) in you project for now.

**Comment by mbergkvist** [comment]
> To fix your issue you can use dep utility (https://github.com/golang/dep) in you project for now.

I'm new to golang, care to explain what I should/could do?

**Comment by mbergkvist** [comment]
`$ dep ensure` did the trick.

**Comment by jkralik** [comment]
Fixed and updated to 1.5.2.
